### PR TITLE
Remove Py_INCREF in numeric.cpp

### PR DESCRIPTION
**Pull request by slel**
Comment 6 in the discussion on Sage Trac ticket 27536
suggests this might fix the memleak reported at #359.

### CODE REVIEW

**Comment by dimpase** [comment]
is it tested in Sage?

**Review by dimpase — CHANGES_REQUESTED** [review]
This leads to an ugly segfault in `src/sage/symbolic/expression.pyx`, so this is not sufficient fix. :-(

**Comment by dimpase** [comment]
here is how the crash looks like
```
...
sage: a=(sqrt(4*(sqrt(3) - 5)*(sqrt(3) + 5) + 48) + 4*sqrt(3))/ (sqrt(3) + 5) ## line 121 ##
sage: a.real_part() ## line 122 ##
4*sqrt(3)/(sqrt(3) + 5)
sage: a.imag_part() ## line 124 ##
2*sqrt(10)/(sqrt(3) + 5)
sage: e1 = sqrt(2)*I - sqrt(2) - 2 ## line 129 ##
sage: e2 = sqrt(2) ## line 130 ##
sage: e1 * e2 ## line 131 ##
------------------------------------------------------------------------
/home/scratch2/dimpase/sage/sage/local/lib64/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0x8174)[0x7fa76acdc174]
/home/scratch2/dimpase/sage/sage/local/lib64/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0x8349)[0x7fa76acdc349]
/home/scratch2/dimpase/sage/sage/local/lib64/python3.7/site-packages/cysignals/signals.cpython-37m-x86_64-linux-gnu.so(+0xa91f)[0x7fa76acde91f]
/lib64/libc.so.6(+0x37ec0)[0x7fa76c387ec0]
/home/scratch2/dimpase/sage/sage/local/lib64/python3.7/site-packages/sage/libs/pynac/pynac.cpython-37m-x86_64-linux-gnu.so(+0x32e42)[0x7fa72575ce42]
/home/scratch2/dimpase/sage/sage/local/lib/libpynac.so.18(_ZNK5GiNaC7numeric5numerEv+0x40)[0x7fa72566fbb0]
/home/scratch2/dimpase/sage/sage/local/lib/libpynac.so.18(_ZNK5GiNaC3add15integer_contentEv+0x8c)[0x7fa72566638c]
/home/scratch2/dimpase/sage/sage/local/lib/libpynac.so.18(_ZNK5GiNaC2ex15integer_contentEv+0x29)[0x7fa725660399]
/home/scratch2/dimpase/sage/sage/local/lib/libpynac.so.18(_ZNK5GiNaC3mul4evalEi+0x98c)[0x7fa7256585dc]
/home/scratch2/dimpase/sage/sage/local/lib/libpynac.so.18(_ZN5GiNaC2ex20construct_from_basicERKNS_5basicE+0x8e)[0x7fa7255b5abe]
/home/scratch2/dimpase/sage/sage/local/lib/libpynac.so.18(_ZN5GiNaCmlERKNS_2exES2_+0x62)[0x7fa725682652]
/home/scratch2/dimpase/sage/sage/local/lib64/python3.7/site-packages/sage/symbolic/expression.cpython-37m-x86_64-linux-gnu.so(_Z55__pyx_f_4sage_8symbolic_10expression_10Expression__mul_P49__pyx_obj_4sage_8symbolic_10expression_ExpressionP7_objecti+0x6c7)[0x7fa7254465d7]
/home/scratch2/dimpase/sage/sage/local/lib64/python3.7/site-packages/sage/structure/element.cpython-37m-x86_64-linux-gnu.so(+0x152de)[0x7fa76b4942de]
/lib64/libpython3.7m.so.1.0(PyNumber_Multiply+0x3e)[0x7fa76c11348e]
/lib64/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x1bab)[0x7fa76c17a3bb]
...
```

**Comment by slel** [comment]
Closing in view of https://github.com/pynac/pynac/issues/364#issuecomment-764773101

**Pull request closed without merging**
