### PR TITLE
Add CI workflow

### PR DESCRIPTION
**Pull request by mkoeppe**
Adding a CI workflow using Sage.

In the first step, we build a source distribution. To make it work on Debian, we also modify `configure.ac` so that it falls back to Debian's renamed library `singular-factory` if `factory` cannot be found.  (This will also make Debian's patch https://salsa.debian.org/science-team/pynac/-/blob/master/debian/patches/find_singular.patch unnecessary.)

### CODE REVIEW

**Comment by mkoeppe** [comment]
A run of the workflow can be seen at https://github.com/mkoeppe/pynac/actions/runs/606909020

**Comment by mkoeppe** [comment]
@dimpase

**Comment by dimpase** [comment]
sure

**Comment by mkoeppe** [comment]
Thanks!

**Pull request merged**
