### PR TITLE
implemented arccoth into ginac functions

### PR DESCRIPTION
**Pull request by rwst**

### CODE REVIEW

**Comment by rwst** [comment]
@aaditya-thakkar I just did the PR for you (by going to your repo, click the branch, and then the PR button). Never did it show 89 files. What was it that you did?

**Comment by aaditya-thakkar** [comment]
I am making a new PR. I actually by mistake added untacked files too.

**Comment by rwst** [comment]
This PR is fine, no need for new PR. Only about style: please type one space after comma.

**Comment by aaditya-thakkar** [comment]
Suggest me if there are any further changes.

**Comment by rwst** [comment]
Thanks. Please pull the new master. Apparently we didn't have a gitignore the whole time. Probably you want to add more files. If so please do PRs for improvement of gitignore too.

**Comment by rwst** [comment]
I just see that besides the crash with `acoth(complex FP)` we might also want to handle unsigned infinity better. SymPy does:
```
>>> coth(0)
zoo
>>> acoth(zoo)
0
```

**Pull request merged**
