### PR TITLE
Add setup.py that builds pynac as a Python extension module

### LINKED ISSUE #361: Repackage pynac as a pip-installable package
Pynac has a compile-time dependency on the Python library but is not installed using Python package infrastructure. This is problematic because Python users cannot install it using standard Python tools - for example for testing different Python versions.

See https://trac.sagemath.org/ticket/30534 for more details.

### PR DESCRIPTION
**Pull request by mkoeppe**
We add a `setup.py`, which builds pynac as a self-contained Python extension module instead of a library.

Fixes #361.

### CODE REVIEW

**Comment by kiwifb** [comment]
This could be done later as clean up but generation of a .pc file that is now never installed should be removed. If I am not mistaken, makefiles will need to be removed as well.

**Comment by mkoeppe** [comment]
As of this PR, you can use the same source to build either the traditional library (using `./configure && make`) or the Python package (using `setup.py`).

**Comment by kiwifb** [comment]
Clever. But ultimately I think the python package should win.

**Comment by mkoeppe** [comment]
At https://trac.sagemath.org/ticket/32386 we are using a different approach now.

**Pull request closed without merging**
