### PR TITLE
implemented arccsch into ginac functions

### PR DESCRIPTION
**Pull request by aaditya-thakkar**
Please review it and suggest if something needs to be changed. :)

### CODE REVIEW

**Comment by rwst** [comment]
With newest master there are merge conflicts, please resolve. This is expected if you submit two branches with changes to the same code region, so better wait with the second in such cases or put it in the first as second commit (no longer possible since I merged it).

So please resolve the merge conflict.

**Comment by aaditya-thakkar** [comment]
solved the merge conflict. :)

**Comment by rwst** [comment]
You might be interested in this doctest fail:
```
sage: asinh(1).n(200)
0.88137358701954302523260932497979230902816032826163541075330
sage: acosh(1).n(200)
0.00000000000000000000000000000000000000000000000000000000000
sage: asech(1).n(200)
0.00000000000000000000000000000000000000000000000000000000000
sage: acsch(1).n(200)
0.881373587019543
```
I don't think it has anything to do with your code, and I'm investigating.

**Comment by aaditya-thakkar** [comment]
Oh, my bad. It didn't come to my attention. I am looking into it.

**Comment by aaditya-thakkar** [comment]
not only for `n(200)` , it is giving the same value for all other values. 
`sage: acsch(1).n(2)
0.881373587019543
sage: acsch(1).n(5)
0.881373587019543
sage: acsch(1).n(10)
0.881373587019543
sage: acsch(1).n(50)
0.881373587019543`

**Comment by aaditya-thakkar** [comment]
I am still not getting the reason but a temporary fix could be ,

if (x.is_equal(_ex1))
                        return asinh(_ex1);
if (x.is_equal(_ex_1))
                        return asinh(_ex_1);

Working fine by adding these lines.

**Comment by rwst** [comment]
That is true but that points to the reason why it happens,  doesn't it? So
we better fix the reason.

**Comment by rwst** [comment]
Why not set a gdb breakpoint at the line and look what inverse()   really does?

**Comment by rwst** [comment]
I will merge this now because per se it is fine. It just triggers a bug in another part which I'll address later. Basically if an `*evalf` function returns a FP value all is well, but here an integer is returned and this gets converted in Sage to default precision. However we can convert any returned values to the desired precision beforehand using `numeric::evalf` which should be done automatically in `function::evalf` in another ticket.

**Pull request merged**
