### PR TITLE
some typos found by codespell

### PR DESCRIPTION
**Pull request by fchapoton**
should be completely harmless

### CODE REVIEW

**Comment by fchapoton** [comment]
Is there anybody out there ? Several pull requests are waiting your attention since some time already.

**Comment by rwst** [comment]
I'm very busy in other areas and would be happy to cede maintainership to anyone I know from the mailing list. Volker is the one with rights to implement that IIRC.

**Comment by fchapoton** [comment]
ok, then maybe you should ask on sage-devel if there is any volunteer ?

**Comment by dimpase** [comment]
LGTM. added to trac #30446 as a fly-by patch

**Pull request merged**
