### PR TITLE
fixed the failed doctest of issue #144 assume::posint

### PR DESCRIPTION
**Pull request by aaditya-thakkar**
Fixed the failing doctest. Please review. :) #144

### CODE REVIEW

**Comment by rwst** [comment]
This may work for the one doctest, but now there are 5 fails in `expression.pyx`:
```
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 1909, in sage.symbolic.expression.Expression.is_real
Failed example:
    t0.is_positive()
Expected:
    False
Got:
    True
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 2460, in sage.symbolic.expression.Expression.__nonzero__
Failed example:
    expr.is_zero()
Expected:
    False
Got:
    True
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 4250, in sage.symbolic.expression.Expression.expand
Failed example:
    (c/2*(5*(3*a*b*x*y*p*q)^2)^(7/2*c)).expand()
Expected:
    1/2*45^(7/2*c)*(a^2*b^2)^(7/2*c)*c*p^(7*c)*q^(7*c)*(x^2)^(7/2*c)*(y^2)^(7/2*c)
Got:
    1/2*45^(7/2*c)*(a^2*b^2)^(7/2*c)*c*p^(7*c)*q^(7*c)*x^(7*c)*y^(7*c)
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 4252, in sage.symbolic.expression.Expression.expand
Failed example:
    ((-(-a*x*p)^3*(b*y*p)^3)^(c/2)).expand()
Expected:
    (a^3*b^3*x^3*y^3)^(1/2*c)*p^(3*c)
Got:
    (a^3*b^3)^(1/2*c)*p^(3*c)*x^(3/2*c)*y^(3/2*c)
**********************************************************************
File "src/sage/symbolic/expression.pyx", line 9009, in sage.symbolic.expression.Expression.simplify_real
Failed example:
    f.simplify_real()
Expected:
    abs(x)
Got:
    x
```

**Comment by aaditya-thakkar** [comment]
Oh, crap! I did a silly mistake. I used `iflags.to_string()=="positive"` as a condition, which can not be used, because it is kind of a key-value pair, not a string. `iflags.get(info_flags::positive)` should have been used I will modify it in a moment. It should work.

**Comment by aaditya-thakkar** [comment]
doctests are passing now in `assumptions.py` and `expression.pyx`.

**Comment by rwst** [comment]
Is fine, thanks for the work.

**Comment by aaditya-thakkar** [comment]
Thanks.

**Pull request merged**
