### PR TITLE
simplify powers with reciprocal logarithm in exponent

### PR DESCRIPTION
**Pull request by behackl**
Related to #134.

### CODE REVIEW

**Comment by behackl** [comment]
This should not be merged yet! After adding these few lines to `power.cpp`, the following happens:

```
sage: bool(1/log(2) == infinity)
Speicherzugriffsfehler (Speicherabzug geschrieben)
```
i.e. a segmentation fault is thrown. I'm quite puzzled: why does this happen?

**Comment by behackl** [comment]
Also, I think that we might want to impose some sort of restriction to this simplification, e.g. only if x is positive or something like that?

```
sage: assume(x > 0)
sage: x^(x/log(x))
e^x
```
should probably work. Not sure yet whether more should be allowed.

**Comment by behackl** [comment]
I've moved the code, that resolves the segmentation fault. Still not entirely sure what happened, but I assume something important happens in the code block where numerical exponents are handled.

I'm not yet checking for positivity, but that'll be the next step.

**Comment by rwst** [comment]
What happened was infinite recursion:
```
#72 0x00007fff2e322a1c in GiNaC::power::eval (this=0x7fffffff9fa0,
    level=<optimized out>) at power.cpp:571
#73 0x00007fff2e2722e6 in GiNaC::ex::construct_from_basic (other=...) at ex.cpp:421
#74 0x00007fff2e31b093 in ex (other=..., this=0x7fffffff9f90) at ex.h:280
#75 GiNaC::operator/ (lh=..., rh=...) at operators.cpp:84
#76 0x00007fff2e322a1c in GiNaC::power::eval (this=0x7fffffffad90,
    level=<optimized out>) at power.cpp:571
#77 0x00007fff2e2722e6 in GiNaC::ex::construct_from_basic (other=...) at ex.cpp:421
#78 0x00007fff2e31b093 in ex (other=..., this=0x7fffffffad80) at ex.h:280
#79 GiNaC::operator/ (lh=..., rh=...) at operators.cpp:84
#80 0x00007fff2e322a1c in GiNaC::power::eval (this=0x7fffffffbb90,
    level=<optimized out>) at power.cpp:571
#81 0x00007fff2e2722e6 in GiNaC::ex::construct_from_basic (other=...) at ex.cpp:421
#82 0x00007fff2e31db9b in ex (other=..., this=0x7fffffffbc10) at ex.h:280
#83 GiNaC::power::evalf (this=<optimized out>, level=<optimized out>,
    parent=<optimized out>) at power.cpp:767
#84 0x00007fff2e29d7fa in evalf (parent=0x0, level=0, this=this@entry=0x0)
    at ex.h:130
#85 GiNaC::infinity::compare_other_type (this=this@entry=0x7fffffffbd40,
    other=..., o=o@entry=GiNaC::relational::equal) at infinity.cpp:258
```
This line caused an infinite loop:
```
571             else if (eexponent.is_equal(1/log(ebasis)))
```
because you construct `power(log(ebasis), -1)` and it is automatically evaluated. You can resolve this by adding `.hold()` I think. You can find such things by starting `sage --gdb`

**Comment by rwst** [comment]
See also https://github.com/sympy/sympy/issues/10676

**Comment by behackl** [comment]
While the current implementation works as far as I can tell, the changes revealed another problem (failing doctest in `expression.pyx`):

```
sage: k.<a> = GF(9)
sage: SR(a+1)^x
Traceback (most recent call last):
...
TypeError: log() takes exactly one argument (0 given)
```

More detailed:
```
sage: SR(a+1)._dbgprinttree()
a + 1 (numeric) @0x2391ef0, hash=0x0, flags=0x7
```
And, in particular:
```
SR(a+1).is_positive()
True
```
Something probably should be done about the conversion from finite fields to SR...

**Comment by rwst** [comment]
Can you please put the finite field case in a new issue?

As to this PR, what do you think about what they say in https://github.com/sympy/sympy/issues/10676? I mean about the negative case.

**Comment by behackl** [comment]
> Can you please put the finite field case in a new issue?

I'll open a new issue in a moment.

> As to this PR, what do you think about what they say in sympy/sympy#10676? I mean about the negative case.

Maybe I was a bit too conservative at first. Our `log` is the principal branch, and the cut in the complex plane is along the negative real axis (s.t. the elements there have argument `pi`). Under these circumstances I'd be for removing the restriction I have implemented right now and allowing the simplification of stuff like `(-1)**(i*pi)` too.

**Comment by behackl** [comment]
I've reverted the commit with the check for positivity and improved the code such that `(-1)^(1/log(-1))` is simplified.

I'm not really sure between the difference of `exponent` and `eexponent`, as well as between `basis` and `ebasis`. I return the first ones, in both cases---but maybe I have to use `ebasis` and `eexponent`? Do you have an idea?

Also (and this might cost a bit more): what should happen with `2^(x + y/log(2))`? It would probably be possible to return `2^x * e^y', but this could also be implemented somewhen later.

**Comment by rwst** [comment]
I think that more complicated rules will have to be handled by a `rewrite` command not automatically. See http://trac.sagemath.org/ticket/10137

As to `expression` vs `eexpression` I have yet to see an ex where it matters.

**Comment by behackl** [comment]
I agree, this is something that might be handled by such a `rewrite` command.

What this branch is currently **not** able to handle is something like
```
sage: (-5)^(3*log(-5))
(-5)^(3*I*pi + 3*log(5))
```
because `log(-5)` gets evaluated before expansion of the power. Not sure how these cases should be handled exactly. Maybe just by dividing the exponent by `log(-5)` and then checking whether the number of operands has decreased?

Also, I'll take care of a supplementary sage branch later. Anything else that should be taken care of here?

**Comment by behackl** [comment]
After reading the argumentation on the sympy ticket, I do have some doubt again whether we should simplify for negative bases. In some sense, this would call for a rewrite function (`rewrite(..., log_principal_branch=True)`), but automatically the simplification should only happen where the result is unique.

**Comment by rwst** [comment]
Which doctests will test the code, I'm not sure? I did (on top of the new pynac/sage branch):
```
sage: 2^(1/log(2))
2^(1/log(2))
sage: assume(x > 0)
sage: x^(x/log(x))
x^(x/log(x))
```

**Comment by rwst** [comment]
Ah no found my error, sorry

**Comment by behackl** [comment]
Thanks! I'll provide a complimentary sage branch tonight!

**Comment by behackl** [comment]
Took me a bit longer, but I've added some doctests now: pynac/sage#2

**Pull request merged**
