### PR TITLE
ginac/numeric.cpp: Only use builtin for smull_overflow if supported

### PR DESCRIPTION
**Pull request by mkoeppe**
Otherwise, we fall back to a version of the code before #378, corrected so that it does not fall into the `abs` trap.

@DaveWitteMorris Does this look OK to you?

Portability tests are running at https://github.com/mkoeppe/pynac/actions/runs/980861323

### CODE REVIEW

**Comment by dimpase** [comment]
I'm testing this on https://trac.sagemath.org/ticket/31585

**Comment by dimpase** [comment]
via https://github.com/sagemath/sagetrac-mirror/actions/runs/982168057

**Comment by dimpase** [comment]
update - https://github.com/sagemath/sagetrac-mirror/actions/runs/982441436 - the previous attempt had wrong file suffix

**Comment by mkoeppe** [comment]
The tests look all good, although the 32-bit tests have not run yet. I have tested locally using `tox -e docker-centos-7-i386-standard` (after using the workaround https://trac.sagemath.org/ticket/32088). The added tests of https://trac.sagemath.org/ticket/31585 are all good. 

Thanks @dimpase for adding me to the project. I am going to merge this PR and create a new release and then update the pynac upgrade ticket.

**Comment by DaveWitteMorris** [comment]
Thanks for fixing this!  The approach looks good to me.  

Minor comment:  Would it be better to pass "result" by reference, rather than by pointer?  (I.e., should the two occurrences of "*result" be changed to "& result" and "result"?)   I am not a C++ programmer, so there is no need to respond to me if you have reasons for doing this the way you did, but I think that would make the signature of smull_overflow be the same on all platforms.  Also, my understanding is that functions that have a pointer argument are supposed to check whether it is null and handle that case intelligently, whereas functions whose argument is passed by reference are not expected to worry about this.

**Comment by mkoeppe** [comment]
`smull_overflow` does have the same signature as the builtin function: It takes two `long`s and a pointer to the result.

**Pull request merged**
