### PR TITLE
implemented trigonometric function combinations

### PR DESCRIPTION
**Pull request by aaditya-thakkar**

### CODE REVIEW

**Comment by rwst** [comment]
I haven't checked every formula but it looks fine, thanks

**Comment by kcrisman** [comment]
I have the dumb question - I assume that these formulas are correct for all legitimate domain values (also complex, or is that relevant here?)...

**Comment by aaditya-thakkar** [comment]
Yes, as far as inverse trig function is defined in that particular domain(including complex), the combination formula works.

**Comment by rwst** [comment]
There are some tests in SymPy's `test_trigonometric.py` which all pass and which I'll include as doctests in the Sage ticket.

**Pull request merged**
