### PR TITLE
simplified trig root expressions

### PR DESCRIPTION
**Pull request by aaditya-thakkar**
This tries to solve issue #146 . @rwst Please have a look at it and suggest if something more needs to be done!

### CODE REVIEW

**Comment by rwst** [comment]
```
sage -t --warn-long 29.8 src/sage/functions/trig.py  # 4 doctests failed
sage -t --warn-long 29.8 src/sage/functions/log.py  # 1 doctest failed
```

**Comment by aaditya-thakkar** [comment]
Do I need to change doctests there and push them to pynac/sage?

**Comment by rwst** [comment]
Yes please use for-pynac-0.6.5. Note you need current Pynac master to
compile cleanly.

**Comment by rwst** [comment]
It seems recent master introduced a bug. Just w2ait a bit until I fixed it.

**Comment by aaditya-thakkar** [comment]
okay, no problem! :)

**Comment by rwst** [comment]
It compiles now but you'll get doctest fails in orthogonal polys. Sorry I had to rush this but the pynac/sage branch already had code that needed this. I uploaded too early to that branch, effectively.

**Comment by aaditya-thakkar** [comment]
Yeah, I see. So should I ignore that paricular doctest fail and push other changes to pynac/sage?

**Comment by rwst** [comment]
yes please

**Comment by aaditya-thakkar** [comment]
I have pulled the recent changes that you made, as soon as `make start` gets done, I will push the changes

**Comment by rwst** [comment]
That branch has the flint change, and every time you switch to develop and back Flint and dependencies get recompiled. That will stop with the next develop because then the patch is included. Of course you need to upgrade old branches that you still need.

**Comment by aaditya-thakkar** [comment]
Done! fixed the doctests and opened the PR. https://github.com/pynac/sage/pull/3

**Comment by rwst** [comment]
Will look at it tomorrow.

**Comment by rwst** [comment]
Thanks.

**Pull request merged**
