### PR TITLE
improve evaluation of trigonometric functions

### PR DESCRIPTION
**Pull request by behackl**
if possible, the argument passed to the trigonometric functions should be reduced according to the period length. this also enables the evaluation of expression containing assumed integers:

```
sage: var('k', domain='integer')
k
sage: sin(k*pi)
0
sage: cos(2*k*pi + pi/3)
1/2
```
and so on. Related to #130.

### CODE REVIEW

**Comment by behackl** [comment]
note: the doctests in `functions/trig.py` pass. I haven't tried a `make ptestlong` or anything in that direction yet.

also: please have a close look at the code; normally I don't do C++. ;-)

**Comment by rwst** [comment]
For some reason the examples you give above do not work.
```
sage: sin(k*pi)
sin(pi*k)
```

**Comment by rwst** [comment]
Ah got my mistake...

**Comment by rwst** [comment]
I think this should not evaluate to floating point:
```
sage: n=SR.var('n', domain='integer')
sage: sin(2*n*pi+4/5)
0.717356090899523
sage: sin(4/5)
sin(4/5)
```
There are a few failing doctests in symbolic but failing in a good way 8)
There is probably a performance hit in `..._eval` which I plan to address when this is merged.

**Comment by rwst** [comment]
As to the C++ please write `) {` instead of `){`,  `const ex` instead of `ex const`.

The FP problem above is because of `&& !x.info(info_flags::crational))` where `x` was not changed to `x_red`. It would have been better in principle to stay with `x`, just for readability, were it not for the possible errors.

**Comment by behackl** [comment]
Thanks for the comments! I've pushed two more commits to fix these issues.

**Comment by rwst** [comment]
Something seems not right:
```
sage: RR=RealField(10)
sage: SR(RR(1)).is_integer()
False
sage: sin(RR(1)*pi)
0
sage: sin(RR(pi))
0.00097
```
This comes from
```
sage: RR(1)*pi-pi
0
```
which is probably fine so we will have to live with such apparent inconsistencies. Moreover with #71 this will all be `0.0000000000` which seems more correct.

Thanks for the work.

**Pull request merged**
