### PR TITLE
implemented reflection at pi/2 -(ref #168)

### PR DESCRIPTION
**Pull request by aaditya-thakkar**
@rwst Here is the new pull request with reference to #168 . Please have a look at it. :)

### CODE REVIEW

**Comment by rwst** [comment]
You didn't test your stuff. I expect you to always do this please.
```
sage -t --warn-long 29.6 src/sage/functions/log.py  # 1 doctest failed
sage -t --warn-long 29.6 src/sage/functions/special.py  # 1 doctest failed
sage -t --warn-long 29.6 src/sage/functions/hyperbolic.py  # 3 doctests failed
sage -t --warn-long 29.6 src/sage/symbolic/expression.pyx  # 3 doctests failed
sage -t --warn-long 29.6 src/sage/symbolic/expression_conversions.py  # 2 doctests failed
sage -t --warn-long 29.4 src/sage/calculus/calculus.py  # 9 doctests failed
sage -t --warn-long 29.4 src/sage/calculus/tests.py  # 1 doctest failed
sage -t --warn-long 29.4 src/sage/calculus/wester.py  # 3 doctests failed
sage -t --warn-long 29.0 src/sage/tests/french_book/mpoly.py  # 1 doctest failed
sage -t --warn-long 29.0 src/sage/tests/french_book/calculus_doctest.py  # 4 doctests failed
```

**Comment by rwst** [comment]
Please also submit at least one example for every function change as doctest to the current pynac/sage branch. Ideally tests should test every possible path of computation but we'll do with one for each of the functions. The doctests should be added to `src/sage/functions/trig.py`

**Comment by aaditya-thakkar** [comment]
@rwst, I have updated the code to fix the errors. It's now passing all the relevant tests. Please have a look at it.

**Comment by aaditya-thakkar** [comment]
Also I have added doctest for each of the function change in pynac/sage. https://github.com/pynac/sage/pull/4

**Comment by rwst** [comment]
Normally,
```
sage: sin((sqrt(pi)+1)*(sqrt(pi)-1))
sin((sqrt(pi) + 1)*(sqrt(pi) - 1))
```
Now
```
sage: sin((sqrt(pi)+1)*(sqrt(pi)-1))
sin(0)
```
The problem is that you only exclude `add`s. That allows much too much. The code should trigger only on a specific form. Which one?

**Comment by aaditya-thakkar** [comment]
@rwst, I think we should check for `is_exactly_a<numeric>(x/pi)`, the code will trigger only if this condition satisfies, this will exclude unnecessary `add`s, `mul`s and other classes to trigger the code . What do you think?

**Comment by rwst** [comment]
Essentially right. Note also that you get this value already here: https://github.com/pynac/pynac/blob/master/ginac/inifcns_trig.cpp#L176 so you need to put your code just after l.178

**Comment by rwst** [comment]
Ah you already had that code positon, well, then just use `ExOverPi`

**Comment by aaditya-thakkar** [comment]
@rwst, Here are the changes. :)

**Comment by aaditya-thakkar** [comment]
@rwst , Anything more needs to be done here?

**Comment by rwst** [comment]
There are bugs showing with the testing (#170)but they existed before the PR so I'm merging.

**Pull request merged**
