### PR TITLE
Fix exp of inverse hyperbolic functions

### PR DESCRIPTION
**Pull request by slel**
This is to fix the bug reported at

- [Sage Trac ticket 31739: Problem with exponential of arctanh and arcosh](https://trac.sagemath.org/ticket/31739)

This is my first contribution to pynac code (and to any C++ code).

Should tests be added somewhere?

Please review.

### CODE REVIEW

**Comment by dimpase** [comment]
Did you try building Sage with thusly changed pynac, and check that it fixes Sage Trac ticket 31739 ?

**Comment by slel** [comment]
Unfortunately I neither tested my changes nor followed the guidelines at

- https://github.com/pynac/pynac/blob/master/CONTRIBUTING.md

Hoping to find time for that at some point, but feel free to take over.

**Comment by slel** [comment]
Thanks. Does Pynac has a way of adding tests?

**Comment by dimpase** [comment]
> Does Pynac have a way of adding tests?

I know as much as you on this :-)

**Comment by rwst** [comment]
Use Sage for testing, pynac is not standalone.

Thanks,

**Pull request merged**
